# .github/workflows/review.yml

# Workflow name
name: "Review"

# Events for the workflow
on:
  pull_request:
    branches:
      - master

# List of jobs
jobs:
  npm-test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --workspaces
